#!/bin/bash

#[ Script ]-------------------------------------------------------------------------------------------------#
#                                                                                                           #
# nrd                                                                                                       #
#                                                                                                           #
# PT-br:                                                                                                    #
# script para registrar quando um deploy foi executado na timeline do NewRelic                              #
#                                                                                                           #
# ----------------------------                                                                              #
#                                                                                                           #
# EN:                                                                                                       #
# script to record deployments in NewRelic's App timeline                                                   #
#                                                                                                           #
# reimlima@gmail.com                                                                                        #
# $Id: nrd,v 1.0 2017/04/24 reimlima Exp reimlima $                                                         #
#                                                                                                           #
#[ License ]------------------------------------------------------------------------------------------------#
#                                                                                                           #
# Copyright (c) 2017 Reinaldo Marques de Lima reimlima@gmail.com                                            #
#                                                                                                           #
# PT-br:                                                                                                    #
# A  permissão  é  concedida, a título gratuito, a qualquer pessoa que obtenha uma   cópia deste software e #
# arquivos de  documentação  associados (o "Software"), para lidar com o Software sem restrição, incluindo, #
# sem limitação,  os  direitos  de  usar,  copiar,  modificar, mesclar, publicar, distribuir, sublicenciar, #
# e / ou vender cópias do Software, e  permitir  que as  pessoas a  quem  o  Software  é fornecido o façam, #
# sujeito às seguintes condições:                                                                           #
#                                                                                                           #
# O  aviso  de  copyright  acima e este aviso de permissão devem ser incluídos em todas as cópias ou partes #
# substanciais do Software.                                                                                 #
#                                                                                                           #
# O  SOFTWARE  É  FORNECIDO  "COMO ESTÁ", SEM GARANTIA  DE QUALQUER TIPO, EXPRESSA OU IMPLÍCITA, INCLUINDO, #
# SEM LIMITAÇÃO, AS GARANTIAS DE COMERCIALIZAÇÃO, ADEQUAÇÃO A UM DETERMINADO FIM E NÃO VIOLAÇÃO. EM  NENHUM #
# CASO  OS  AUTORES  OU  DIREITOS  AUTORAIS TITULARES  SERÃO RESPONSÁVEIS POR QUALQUER RECLAMAÇÃO, DANOS OU #
# OUTRAS RESPONSABILIDADES, SEJA EM UMA  AÇÃO DE CUMPRIMENTO DE CONTRATO  OU  DE  OUTRA  FORMA,  DECORRENTE #
# DE, OU EM CONEXÃO COM O SOFTWARE OU O USO OU OUTRAS FUNÇÕES DO SOFTWARE.                                  #
#                                                                                                           #
# Exceto  conforme  contido  no  presente aviso, o nome do(s) dos detentores de direitos autorais acima não #
# devem ser utilizados em publicidade ou de outra forma  para  promover  a venda, uso ou outras negociações #
# deste Software sem autorização prévia por escrito.                                                        #
#                                                                                                           #
# ----------------------------                                                                              #
#                                                                                                           #
# EN:                                                                                                       #
# Permission  is  hereby  granted, free  of  charge,  to  any  person obtaining a copy of this software and #
# associated  documentation  files (the "Software"), to deal in the Software without restriction, including #
# without  limitation  the  rights  to  use,  copy, modify, merge, publish, distribute, sublicense,  and/or #
# sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to #
#the following conditions:                                                                                  #
#                                                                                                           #
# The  above  copyright  notice  and  this permission notice shall be included in all copies or substantial #
# portions of the Software.                                                                                 #
#                                                                                                           #
# THE  SOFTWARE  IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,  INCLUDING BUT NOT  #
# LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS  FOR  A  PARTICULAR  PURPOSE AND  NONINFRINGEMENT.  #
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS  BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER  LIABILITY, #
# WHETHER  IN  AN  ACTION  OF  CONTRACT, TORT  OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE #
#SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                                                     #
#                                                                                                           #
# Except  as  contained  in  this  notice,  the name(s) of the above copyright holders shall not be used in #
# advertising  or  otherwise  to  promote  the  sale,  use or other dealings in this Software without prior #
# written authorization.                                                                                    #
#                                                                                                           #
#[ Changelog ]----------------------------------------------------------------------------------------------#
#                                                                                                           #
# [24/04/2017] - v1     - First Stable Release                                                              #
#                                                                                                           #
#-----------------------------------------------------------------------------------------------------------#

#[ Variables ]----------------------------------------------------------------------------------------------#

JQ=$(which jq)
AWK=$(which awk)
SED=$(which sed)
DATE=$(which date)
CURL=$(which curl)
SCRIPTNAME=$(basename $0)
# script conf file. Set here the full path like "/etc/nrd/nrd.conf"
SCRIPTCONFFILE="nrd.conf"

#[ Functions ]----------------------------------------------------------------------------------------------#

exiterrorfunc(){
	# Generic output function, show the message given,
	# and then exits with the given code.

	# Parse message and exit code
	EXITCODE=$(echo $@ | $AWK '{print $NF}')
	EXITMESSAGE=$(echo $@ | $AWK '{ $NF = ""; print $0}')
	echo "[ $($DATE +%m/%d/%Y\ %H:%M:%S) ] - $EXITMESSAGE"
	exit $EXITCODE
}

usage(){
	echo "
	usage:
	$SCRIPTNAME -a <app> -c <changelog> -d <description> -r <revision> -u <user>

	app: App Name (duh)
	changelog: file added, file changed, file removed, etc
	description: quick description about some new behavior or so
	revision: Revision Number
	user: User who made the deploy

	Notice: Remember to use quotation marks in changelog and description, you know, for best practices

	Example:
	$SCRIPTNAME -a myapp -c \"Added: index.php, Removed: None\" -d \"Index Added for the new site\" -r \"001\" -u \"developer@example.com\"
	"
	exiterrorfunc "Invalide Arguments given 1"
}

getIdByName(){
	APP_NAME_TEST=$($CURL -s -X GET 'https://api.newrelic.com/v2/applications.json' -H "X-Api-Key:${API_KEY}" | $JQ '.applications[].name' | $SED 's/"//g' | $SED "/^$APP_NAME$/!d")

	if [[ $APP_NAME_TEST != "" ]]; then
		APP_ID=$($CURL -s -X GET 'https://api.newrelic.com/v2/applications.json' -H "X-Api-Key:${API_KEY}" -d "filter[name]=$APP_NAME" | $JQ '.applications[0].id')
	fi

	if [[ $APP_ID ]]; then
		return $APP_ID
	else
		return 0
	fi
}

recordDeployment(){
	$CURL -X POST "https://api.newrelic.com/v2/applications/${APP_ID}/deployments.json" \
	     -H "X-Api-Key:${API_KEY}" -i -H "Content-Type: application/json" \
	     -d "{ \"deployment\": { \"revision\": \"$DEPLOY_REVISION\", \"changelog\": \"$DEPLOY_CHANGELOG\", \"description\": \"$DEPLOY_DESCRIPTION\", \"user\": \"$DEPLOY_USER\" } }"
	if [[ $? -eq 0 ]]; then
		exiterrorfunc "Deploy was marked successfully 0"
	else
		exiterrorfunc "Something went wrong, see NewRelic Status in https://status.newrelic.com/ 1"
	fi
}

executionFlow(){
	getIdByName $APP_NAME
	if [[ $APP_ID -ne 0 ]]; then
		recordDeployment $APP_ID $DEPLOY_CHANGELOG $DEPLOY_DESCRIPTION $DEPLOY_REVISION $DEPLOY_USER
	else
		exiterrorfunc "Something went wrong, invalid App Name: $APP_NAME 1"
	fi
}

#[ Load conf file ]-----------------------------------------------------------------------------------------#

if [ -e $SCRIPTCONFFILE ] ; then
        source $SCRIPTCONFFILE
else
        exiterrorfunc "ERROR: $SCRIPTCONFFILE file not found 1"
fi

[[ $API_KEY ]] || exiterrorfunc "API_KEY not found in $SCRIPTCONFFILE 1"
[[ $JQ ]] || exiterrorfunc "Unable to find 'jq' command, please install it in https://stedolan.github.io/jq/ 1"

#[ Load commandline options ]-------------------------------------------------------------------------------#

[[ $# -ne 10 ]] && usage

while getopts "a:c:d:r:u:" opts ; do
	case $opts in
		a) APP_NAME=$OPTARG ;;
		c) DEPLOY_CHANGELOG=$OPTARG ;;
		d) DEPLOY_DESCRIPTION=$OPTARG ;;
		r) DEPLOY_REVISION=$OPTARG ;;
		u) DEPLOY_USER=$OPTARG ;;
		*) exiterrorfunc "Something went wrong, use a valid argument 1" ;;
	esac
done

executionFlow $@
